package app.binar.synrgy.android.finalproject.utils

object DummyBearer {
    val auth = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6ImludmVzdG9yQGZ1bmRyYWlzZXkuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYzOTc3MTgxOCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9JTlZFU1RPUiJdLCJqdGkiOiI1OGNlOTA2NS0yMmRlLTRlYmYtOTBlZi03MzNkNTExMzIwNjIiLCJjbGllbnRfaWQiOiJjbGllbnQtd2ViIn0.9yXNYx4Qh_M-aDWU3NsFYFhKDDfOg5PNHzZBcStSjW8"
}