package app.binar.synrgy.android.finalproject.utils

object DummyBearer {
    val auth =
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6ImludmVzdG9yQGZ1bmRyYWlzZXkuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYzOTQ3MjcwNSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9JTlZFU1RPUiJdLCJqdGkiOiJhMGFjYmE3My1hOGViLTQzMDItODBlOS1iYjBiODQxMGUwYmIiLCJjbGllbnRfaWQiOiJjbGllbnQtd2ViIn0.hm-Sc5Y-Eugi9jE4rgN1rc5z6wAMxf5WJGGFqVFFZDM"
}