package app.binar.synrgy.android.finalproject.utils

object DummyBearer {
    val auth = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6ImludmVzdG9yQGZ1bmRyYWlzZXkuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYzOTkwMDIyNywiYXV0aG9yaXRpZXMiOlsiUk9MRV9JTlZFU1RPUiJdLCJqdGkiOiJmYTUzMDA2OS0xMGFkLTRkZTItOWMyOC1iOWY1YTBhYjZiZjEiLCJjbGllbnRfaWQiOiJjbGllbnQtd2ViIn0.v7KsPtl3LaV0FokcXv2cHUB_jdyrMaDMYJzLnd-lb28"
}